DROP TABLE IF EXISTS treco;
CREATE TABLE treco (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	name VARCHAR(63),
	description VARCHAR(127),
	status VARCHAR(31) DEFAULT 'on'
);

DROP TABLE IF EXISTS employe;
CREATE TABLE employe (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(127),
        email VARCHAR(255),
        password VARCHAR(63)
);
